site_name: The SwarmUS Project
site_url: https://swarmus.github.io/SwarmUS-doc/
repo_url: https://github.com/SwarmUS/
repo_name: SwarmUS
edit_uri: ""
copyright: Copyright &copy; 2021 - SwarmUS

nav:
  - Home: "index.md"
  - User Guides:
      - User Guides Home: "sections/user-guide/index.md"
      - Basic Examples:
          - Flashing an LED Using Buzz: "sections/user-guide/basic-examples/led-flash-buzz.md"
          - Flashing an LED on a remote Hiveboard: "sections/user-guide/basic-examples/led-flash-remote-hiveboard.md"
          - Controlling a Robot Using Buzz and HiveMindBridge: "sections/user-guide/basic-examples/buzz-control-robot.md"
          - Calling functions from HiveAR: "sections/user-guide/basic-examples/hivear-call-functions.md"
          - Acquiring a remote Hiveboard's position: "sections/user-guide/basic-examples/basic-interloc.md"
      - Follow the leader example:
          - Introduction to the use-case: "sections/user-guide/follow-the-leader/index.md"
          - "Adding Buzz scripts to the mix": "sections/user-guide/follow-the-leader/buzz-scripts-getting-started.md"
  - Reference:
      - Reference Home: "sections/reference/index.md"
      - Architecture of the System: "sections/reference/architecture.md"
      - Buzz:
          - Available APIs: "sections/reference/Buzz/available-apis.md"
      - HiveMind:
          - About HiveMind: "sections/reference/HiveMind/hivemind-preface.md"
          - HiveMind and the Host: "sections/reference/HiveMind/hivemind-host.md"
          - HiveMind and the Swarm: "sections/reference/HiveMind/hivemind-swarm.md"
          - HiveMind API: "sections/reference/HiveMind/hivemind-api.md"
          - BittyBuzz Virtual Machine: "sections/reference/HiveMind/bbzvm/index.md"
      - HiveMindBridge:
          - About HiveMindBridge: "sections/reference/HiveMindBridge/about-hivemindbridge.md"
          - Registering Custom Actions: "sections/reference/HiveMindBridge/registering-custom-actions.md"
          - Defining Callbacks: "sections/reference/HiveMindBridge/defining-callbacks.md"
          - Defining Manifests: "sections/reference/HiveMindBridge/defining-manifests.md"
          - Example Logger Implementation: "sections/reference/HiveMindBridge/logger.md"
      - Networking:
          - Configuring the Wi-Fi network: "sections/reference/Networking/configure-wifi.md"
          - HiveConnect: "sections/reference/Networking/hiveconnect.md"
  - Hardware:
      - Hardware Home: "sections/hardware/index.md"
      - Available UI: "sections/hardware/hiveboard-ui.md"
  - About: "sections/about/about.md"

theme:
  name: material
  palette:
    - scheme: slate
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.top
  logo: assets/SVG_S_Swarm_Abeille.svg
  favicon: assets/SVG_S_Swarm_Abeille.svg
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/swarmus/
    - icon: fontawesome/brands/github
      link: https://github.com/SwarmUS
  disqus: swarmus

extra_css:
    - css/extra.css

markdown_extensions:
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
