site_name: The SwarmUS Project
site_url: https://swarmus.github.io/SwarmUS-doc/
repo_url: https://github.com/SwarmUS/
repo_name: SwarmUS
edit_uri: ""
copyright: Copyright &copy; 2021 - SwarmUS

nav:
  - Home: "index.md"
  - User Guides:
      - User Guides Home: "sections/user-guide/index.md"
      - Basic Examples:
          - Flashing an LED Using Buzz: "sections/user-guide/basic-examples/led-flash-buzz.md"
          - Flashing an LED on a remote Hiveboard: "sections/user-guide/basic-examples/led-flash-remote-hiveboard.md"
          - Writing "Hello World" to a robot: "sections/user-guide/basic-examples/hello-world-bridge.md"
          - Calling functions from HiveAR: "sections/user-guide/basic-examples/hivear-call-functions.md"
          - Acquiring a remote Hiveboard's position: "sections/user-guide/basic-examples/basic-interloc.md"
      - Follow the leader example:
          - Introduction to the use-case: "sections/user-guide/follow-the-leader/index.md"
          - "HiveMindBridge: Getting Started": "sections/user-guide/follow-the-leader/hivemind-bridge-getting-started.md"
          - "Adding Buzz scripts to the mix": "sections/user-guide/follow-the-leader/buzz-scripts-getting-started.md"
  - Developer Guides:
      - Developer Guides Home: "sections/developer-guide/index.md"
  - Reference:
      - Reference Home: "sections/reference/index.md"
      - HiveMind:
          - HiveMind preface: "sections/reference/HiveMind/hivemind-preface.md"
          - HiveMind and the Host: "sections/reference/HiveMind/hivemind-host.md"
          - HiveMind and the Swarm: "sections/reference/HiveMind/hivemind-swarm.md"
          - HiveMind API: "sections/reference/HiveMind/hivemind-api.md"
          - BittyBuzz Virtual Machine: "sections/reference/HiveMind/bbzvm/index.md"
      - HiveMindBridge:
          - Registering Custom Actions: "sections/reference/HiveMindBridge/registering-custom-actions.md"
          - Defining Callbacks: "sections/reference/HiveMindBridge/defining-callbacks.md"
          - Defining Manifests: "sections/reference/HiveMindBridge/defining-manifests.md"
          - Example Logger Implementation: "sections/reference/HiveMindBridge/logger.md"
  - Hardware:
      - Hardware Home: "sections/hardware/index.md"
  - About: "sections/about/about.md"

theme:
  name: material
  palette:
    - scheme: slate
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.top
  logo: assets/SVG_S_Swarm_Abeille.svg
  favicon: assets/SVG_S_Swarm_Abeille.svg
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/swarmus/
    - icon: fontawesome/brands/github
      link: https://github.com/SwarmUS
  disqus: swarmus
